services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB : tiny_ledger
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
volumes:
  db-data: