services:
  db:
    image: postgres:latest
    container_name: social-pg-db
    environment:
      POSTGRES_DB : ${POSTGRES_DB} 
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT}:${DB_PORT}"
volumes:
  db-data: